config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :posts,               only: [:index, :show, :create, :destroy] do
    resources :comments,          only: [:index, :create, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
  %nav
    %ul
      %li= link_to "About", about_path
      %li= link_to "Contact", contact_path
      %li
        %a{:href => "http://news.railstutorial.org/"} News

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to "photo ocean", root_path, id: "logo"
    %nav
      .navbar-header
        %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
      %ul#bs-example-navbar-collapse-1.nav.navbar-nav.navbar-right.collapse.navbar-collapse
        %li= link_to "Home", root_path
        %li= link_to "Help", help_path
        %li= link_to "Users", users_path
        - if logged_in?
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Account
              %b.caret
            %ul.dropdown-menu
              %li= link_to "Profile", current_user
              %li= link_to "Edit profile", edit_user_path(current_user)
              %li.divider
              %li
                = link_to "Log out", logout_path, method: :delete
        - else
          %li= link_to "Log in", login_path
          %li= link_to "Sign up", new_user_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        = content_tag(:div, message, class: "alert alert-#{message_type}")
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?